baseURL = "localhost"
languageCode = "en-us"
title = "Hugo-Docs"
theme="hello-friend-ng"
pagenate = 10

[params]
  # Subtitle for home
  homeSubtitle = "markdown files manegement site"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog,Hugo-doc"
  images = [""]

  [languages]
    [languages.en]
      title = "hugo-docs"
      subtitle = "markdown files manegement site"
      keywords = ""
      copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
      readOtherPosts = "Read other posts"

      [languages.en.params.logo]
        logoText = "cd HOME"
        logoHomeLink = "/"
      # or
      #
      # path = "/img/your-example-logo.svg"
      # alt = "Your example logo alt text"

    # And you can even create generic menu
    [[menu.main]]
      identifier = "files"
      name       = "Files"
      url        = "/posts"
